version: "3"

services:
  api:
    build:
      context: .
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - '7017:7017'
    volumes:
      - "mongodb:/data/db"


volumes:
  mongodb: